AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DataBucketName:
    Type: String
    AllowedPattern: '(?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$'
    Description: >-
      The name of the amazon s3 Bucket where the order data should be stored .
      (Name should be unique and only contains lower case leters , numericals
      and '-' .)
  DynamoTableName:
    Type: String
    Description: >-
      The name of the amazon  Dynamodb Table where the validated order data will
      be stored (Between 3 and 255 characters, containing only letters, numbers,
      underscores (_), hyphens (-), and periods (.).)
  ScriptlocationAdd:
    Type: String
    Description: The location of the python script stored in amazon s3 bucket .
  SNSsubscriptionMail:
    Type: String
    Description: The email address for recieving the SNS allert .
  SESsendersMail:
    Type: String
    Description: The email address for sending the mail regarding the faults in order data.
  SESRecieversMail:
    Type: String
    Description: >-
      The email address for recieving the mail regarding the faults in order
      data .
  GlueJobName:
    Type: String
    Description: The name of AWS Glue job.
Resources:
  DataBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref DataBucketName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 33ff3b0f-cd12-47ba-9005-0ff7a0f7bbb4
  Ordertable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DynamoTableName
      AttributeDefinitions:
        - AttributeName: Order_Id
          AttributeType: S
      KeySchema:
        - AttributeName: Order_Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 22972dcf-69de-41c9-b4fc-14d970ef5820
  MyOrderRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0ce6a7aa-4b53-4def-bdb1-558f38227906
  OrderSNSMail:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: !Ref SNSsubscriptionMail
          Protocol: email
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8d938284-e4ee-43db-97d9-954d11ae166a
  MyOrderJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: 3.9
        ScriptLocation: !Ref ScriptlocationAdd
      DefaultArguments:
        '--job-bookmark-option': job-bookmark-enable
        '--bucketname': !Ref DataBucketName
        '--tablename': !Ref DynamoTableName
        '--RecieversMail': !Ref SESRecieversMail
        '--SendersMail': !Ref SESsendersMail
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Role: !Ref MyOrderRole
      Name: !Ref GlueJobName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 722f9180-4347-46b2-9ece-b3723edac1ef
  ScheduleJobtrigger:
    Type: 'AWS::Glue::Trigger'
    Properties:
      Type: SCHEDULED
      Description: DESCRIPTION_SCHEDULED
      Schedule: cron(0/60 * * * ? *)
      Actions:
        - JobName: !Ref GlueJobName
          Arguments:
            '--job-bookmark-option': job-bookmark-enable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d63f9f63-ae60-4654-a9d7-b8de7d9b2a80
  Eventbridges:
    Type: 'AWS::Events::Rule'
    Properties:
      EventBusName: default
      EventPattern:
        detail-type:
          - Glue Job State Change
        source:
          - aws.glue
        detail:
          jobName:
            - !Ref GlueJobName
          state:
            - FAILED
      State: ENABLED
      Targets:
        - Arn: !Ref OrderSNSMail
          Id: Id1739prudwi
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 80f40af2-e1e0-49f8-829c-af76812cb923
  SenderEmail:
    Type: 'AWS::SES::EmailIdentity'
    Properties:
      EmailIdentity: !Ref SESsendersMail
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0a4e787e-252d-4eb7-b814-8df632615192
  RecieverEmail:
    Type: 'AWS::SES::EmailIdentity'
    Properties:
      EmailIdentity: !Ref SESRecieversMail
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4797883a-ce40-412d-8e85-8c4353547eef
  SNSTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          Sid: AWSEvents_Job_failure_Allert_Id4710798f-6bdf-4d11-9987-af278c9b99bd
          Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action:
            - 'sns:Publish'
          Resource: !Ref OrderSNSMail
      Topics:
        - !Ref OrderSNSMail
    Metadata:
      'AWS::CloudFormation::Designer':
        id: cbe54e9b-56f9-4641-b691-ca6a6e96295d
Metadata:
  'AWS::CloudFormation::Designer':
    4797883a-ce40-412d-8e85-8c4353547eef:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    0a4e787e-252d-4eb7-b814-8df632615192:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
    d63f9f63-ae60-4654-a9d7-b8de7d9b2a80:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 210
      z: 1
      embeds: []
    8d938284-e4ee-43db-97d9-954d11ae166a:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 210
      z: 1
      embeds: []
    cbe54e9b-56f9-4641-b691-ca6a6e96295d:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 8d938284-e4ee-43db-97d9-954d11ae166a
    80f40af2-e1e0-49f8-829c-af76812cb923:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 210
      z: 1
      embeds: []
    0ce6a7aa-4b53-4def-bdb1-558f38227906:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 330
      z: 1
      embeds: []
    722f9180-4347-46b2-9ece-b3723edac1ef:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 330
      z: 1
      embeds: []
    22972dcf-69de-41c9-b4fc-14d970ef5820:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 330
      z: 1
      embeds: []
    33ff3b0f-cd12-47ba-9005-0ff7a0f7bbb4:
      size:
        width: 60
        height: 60
      position:
        x: 420
        'y': 90
      z: 1
      embeds: []
